# -*- coding: utf-8 -*-
"""Decision making.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cmX8KtgMkJU0s9v22RHDab6M6BZBaSc3

# 1. Find the largest among two numbers
"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
if a>b:
  print(a,"is greatest")
else:
  print(b,"is greatest")

"""# 2. Check whether the number is even or odd"""

num=int(input("Enter a number to check:"))
if num%2==0:
  print(num,"is an even number")
else:
  print(num,"is not an even number")

"""# 3. Check whether a number is positive , negative or zero

"""

num=int(input("Enter a number to check:"))
if num>0:
  print(num,"is a positive number")
if num<0:
  print(num,"is a negative number")
if num==0:
  print(num,"is zero")

"""# 4. Check whether a number is two digit or not"""

num=int(input("Enter a number:"))
if num>9 and num<100:
  print(num,"is a two digit number")
else:
  print(num,"not a two digit number")

"""# 5. Check the nature of solution of quadratic equations"""

a=int(input("Enter coefficient of x2:"))
b=int(input("Enter coefficient of x:"))
c=int(input("Enter constant term :"))
d=(b**2)-(4*a*c)
if d>=0:
  if d>0:
    print("Quadratic equation have two real solutions")
  if d==0:
    print("Quadratic equation has two equal solutions")
if d<0:
  print("Quadratic equation has no real solutions")

"""# 6. Find the smallest number among three numbers"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
if a<b and a<c:
  print(a,"is smallest number")
elif b<a and b<c:
  print(b,"is smallest number")
else:
  print(c,"is smallest number")

"""# 7. Find the smallest number in a two digit number"""

num=int(input("Enter a two digit number:"))

b=num%10
c=num//10
if b==c:
  print("is equal")
if b<c:
  print(b,"is smallest")
if c<b:
  print(c,"is smallest")

"""# 8. Check whether a number divisible by another"""

a=int(input("Enter a number :"))
b=int(input("Enter a number to check divisibility:"))
if a%b==0:
  print(a,"is divisible by",b)
else:
  print(a,"is not divisible by",b)

"""# 9. Find the distance between two points on a number line"""

x1=int(input("Enter first point:"))
x2=int(input("Enter second point: "))
if x1==x2:
  print("Distance is 0")
else:
  d=((x2-x1)**2)**(1/2)
  print("Distance between two points is==",d)

"""# 10. Check whether a year is leap year or not"""

year=int(input("Enter a year:"))
rem1=year%4
if rem1==0:
  rem2=year%4
  if rem2==0:
    print(year,"is a leap year")
  else:
    rem3=rem2%4
    rem4=rem2%100
    if rem3==0 and rem4!=0:
      print(year,"is a leap year")
    else:
      print(year," not a leap year")
else:
  print(year,"not a leap year")