# -*- coding: utf-8 -*-
"""Loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtQbLO7DMaJWXgQFMGZMcTf7kyPAxBP8

# 1. Find the first n odd numbers
"""

n=int(input("Enter the limit:"))
i=1
while(i<=n):
  print(i)
  i=i+2

"""# 2. Check whether a number is palindrome or not

"""

n=int(input("Enter a number:"))
temp=n
rev=0
while(n>0):
  digit=n%10
  rev=rev*10+digit
  n=n//10
if temp==rev:
  print(rev,"is a palindrome")
else:
  print(rev,"not a palindrome")

"""# 3. Convert a binary number to its decimal equivalent"""

num=int(input("Enter a number to convert:"))
b=0
c=num
while(num>0):
  num=num//10
  b=b+1
dec=0
i=0
while(i<b):
  rem=c%2
  dec=dec+(2**i*rem)
  c=c//10
  i=i+1
print("The converted decimal equivalent is:",dec)

"""# 4. Find the sum of first n natural numbers"""

n=int(input("Enter the limit:"))
sum=0
i=1
while(i<=n):
  sum=sum+i
  i=i+1
print("Sum of first n natural numbers:",sum)

"""# 5. Find the reverse of a number"""

num=int(input("Enter the number:"))
rev=0
while(num>0):
  digit=num%10
  rev=rev*10+digit
  num=num//10
print("Reversed number is:",rev)

"""# 6. Find the factorial of a given number"""

num=int(input("Enter the number:"))
fact=1
while(num>0):
  fact=fact*num
  num=num-1
print("Factorial is:",fact)

"""# 7. Check whether a number is Automorphic or not"""

num=int(input("Enter the number to check:"))
temp=num
b=0
while(temp>0):
  temp=temp//10
  b=b+1
sqr=num*num
i=0
count=0
digit=0
while(i<b and count<b):
  rem=sqr%10
  digit=digit+10**i*rem
  sqr=sqr//10
  i=i+1
  count+=1
if(num==digit):
  print("The number",num, "is automorphic")
else:
  print("The number",num, "is  not automorphic")

"""# 8. Find the sum of factors of a number"""

num=int(input("Enter the number:"))
sum=0
for i in range(1,num+1):
  if num%i==0:
    sum=sum+i
print("Sum of factors is:",sum)

"""# 9. Compute the GCD of two numbers"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
gcd=0
i=1
while(i<=a and i<=b):
  re1=a%i
  re2=b%i
  if(re1==0 and re2==0):
    gcd=gcd+1
  i=i+1
print("GCD=",gcd)

"""# 10. Check whether a number is Armstrong or not"""

num=int(input("Enter the number:"))
a=num
temp=num
b=0
while(temp>0):
  temp=temp//10
  b=b+1
sum=0
while(num>0):
  digit=num%10
  sum=sum+digit**b
  num=num//10
if(sum==a):
  print(a,"is an armstrong number")
else:
  print(a,"is not an armstrong number")

"""# 11. Compute the squares of natural numbers between two numbers"""

n1=int(input("Enter the lower limit:"))
n2=int(input("Enter the upper limit:"))
for i in range(n1,n2):
  pro=i**2;
  print(pro)

"""# 12. Compute the sum upto series of 1-4+9-16"""

n1=int(input("Enter the lower limit:"))
n2=int(input("Enter the upper limit:"))
sum=0
for i in range(n1,n2+1):
  pro=i**2
  if pro%2==0:
    sum=sum-pro
  else:
    sum=sum+pro
print("Sum of series:",sum)

"""# 13. Compute x^n"""

base=int(input("Enter the base number:"))
power=int(input("Enter the power:"))
pro=1
for i in range(power):
  pro=pro*base
print(pro)

"""# 14. Generate the fibonacci series"""

n=int(input("Enter the number of terms:"))
n1=0
n2=1
n3=0
count=0
if n<3:
  if n==1:
    print(n1)
  else:
    print(n1)
    print(n2)
else:
   for i in range(n):
    print(n1)
    n3=n1+n2
    n1=n2
    n2=n3
    count+=1