# -*- coding: utf-8 -*-
"""Sequential programs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezMQ-IydhHpCmCLtvaBrEmCoMYwOywfE
"""



"""# 1. Find the sum of two numbers


"""

a=int(input("Enter the value for a:"))
b=int(input("Enter the value for b:"))
sum=a+b
print("Sum=",sum)

"""# 2. Calculate the area and perimeter of triangle
bold text
"""

a=float(input("Enter first side:"))
b=float(input("Enter second side:"))
c=float(input("Enter third side:"))
p=a+b+c
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**(1/2)

print("PERIMETER OF TRIANGLE=",p)
print("AREA OF TRIANGLE=",area)

"""## 3. Calculate the area of circle"""

r=float(input("Enter radius:"))
area=3.14*r*r
print("AREA OF CIRCLE=",area)

"""# 4. Calculate the sum and average of three numbers"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
sum=a+b+c
avg=sum/3
print("SUM=",sum)
print("AVERAGE=",avg)

"""# 5. Calculate the number of years, months, and days from a given number of days

"""



day=int(input("Enter the number of days:"))
year=day//365
month=day//30
week=day//7
print("YEAR=",year,"\n MONTH=",month,"\n WEEK=",week)

"""# 6. Convert seconds to hour, minute and seconds"""

sec=int(input("Enter the time in seconds:"))
hour=sec//3600
min=sec//60
print("HOUR=",hour,"\n MINUTE=",min)

"""# 7. Calculate sum, difference, product and quotient of two numbers

"""

a=int(input("Enter a number:"))
b=int(input("Enter another number:"))
print("Sum=",a+b)
print("Difference=",a-b)
print("Product=",a*b)
print("Quotient=",a//b)

"""# 8. Find the roots of quadratic equations"""

a=int(input("Enter coefficient of x2:"))
b=int(input("Enter coefficient of x:"))
c=int(input("Enter constant term:"))
D=b**2-(4*a*c)
r1=(b-(D)**(1/2))/2*a
r2=(b+(D)**(1/2))/2*a
print("ROOTS ARE:\n",r1,"\n",r2)

"""# 9. Calculate the percentage of 5 subjects"""

s1=float(input("Enter the marks of English:"))
s2=float(input("Enter the marks of OOP:"))
s3=float(input("Enter the marks of CT:"))
s4=float(input("Enter the marks of EVS:"))
s5=float(input("Enter the marks of Maths:"))
total=s1+s2+s3+s4+s5
percent=(total/500)*100
print("TOTAL MARKS =",total)
print("PERCENT=",percent)

"""# 10. Convert Celsius to Fahrenheit"""

c=float(input("Enter the degree in celsius:"))
f=c*1.8+32
print("Temperature in Fahrenheit=",f)